spring:
  datasource:
    url: jdbc:sqlserver://DESKTOP-NPE7T4B\SQLSERVEREDDY;databaseName=products;trustServerCertificate=true
    username: ${db_user}
    password: ${db_pass}
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
  boot:
    admin:
     client:
      uri: http://localhost:8090/
server:
  port: 8080
  error:
    include-message: always
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8088/eureka/
management:
  endpoints:
    web:
      exposure:
       include: "*"